### ISSUE TITLE
Add a manual for newbies or a wiki

### ISSUE THREAD

**Issue by cpcbegin** [rsta2/cpmemu#1]
It's difficult to start the emulator without a guide to configure step by step.

**Comment by rsta2** [comment]
I know that CPMemu is not easy to set-up. One should have some CP/M knowledge from the past and should deal with the Circle project (for bare metal use) to be able to get it running.

Unfortunately writing docs is not my favourite task. What I can do at the moment I have done by writing the INSTALL and INSTALL.linux files. If you have specific suggestions, which part of these files should be improved in some way, please let me know!

**Comment by cpcbegin** [comment]
I think you can open a wiki in the project, although empty, users can fill it with our findings.
By the way I'm going to use like another linux program not as bare metal... by the moment.

**Comment by rsta2** [comment]
OK, the wiki is open.

**Comment by rsta2** [comment]
There was no significant wiki entry in over half a year. I have closed it again.
