### ISSUE TITLE
Mount a second floppy image to CP/M

### ISSUE THREAD

**Issue by ritterob** [rsta2/cpmemu#2]
It appears that the program is hard-coded to support only one disk called cpmdisk.bin. Is there a way use an additional image for a two-disk system?

**Comment by rsta2** [comment]
Yes, at the moment only one disk image is supported. If this is important for you, I will have a look, how a second disk (drive B:) can be added, when I have some spare time.

**Comment by ritterob** [comment]
Thanks. Since the A drive went out on my Kaypro 4 I don't have access to my CP/M any more. A PI with CP/M and two floppies would be great.

**Comment by rsta2** [comment]
OK, I will modify CPMemu so that a second disk image can be used as drive B:. This will take some time.

**Comment by rsta2** [comment]
I have updated CPMemu so that a second disk drive image (B:) is supported now. The (optional) disk image file for drive B: is named *cpmdisk2.bin*. Be sure to update the file *system.bin*. See the appended UPDATE section in the files *INSTALL* or *INSTALL.linux* for details! Comments are welcome.

**Comment by ritterob** [comment]
Thanks! That's a big help.
